version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    working_directory: ~/frontend_app
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm test

  build-node:
    # Build node projects
    executor: node/default
    working_directory: ~/frontend_app
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Build
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy build output to artifacts directory
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploy your app here"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-node
      - test-node:
          requires:
            - build-node