version: 2.1
executors:
  build-node:
    docker:
      - image: cimg/node:16.20.2  # Use a specific version
    working_directory: ~/project
  test-node:
    docker:
      - image: cimg/node:16.20.2  # Use a specific version
    working_directory: ~/project

jobs:
  build-node:
    executor: build-node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd BackendAPI/functions
            npm install

  test-node:
    executor: test-node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd BackendAPI/functions
            npm install
      - run:
          name: Check if Jest is installed
          command: |
            cd BackendAPI/functions
            npm list jest
      - run:
          name: Run Tests
          command: |
            cd BackendAPI/functions
            npm test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploy your app here"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-node
      - test-node:
          requires:
            - build-node
      - deploy:
          requires:
            - test-node