version: 2.1
executors:
  build-node:
    docker:
      - image: cimg/node:16.20.2
    working_directory: ~/project/BackendAPI/functions  # Explicitly set working directory

jobs:
  build-node:
    executor: build-node
    steps:
      - checkout
      - run:
          name: Verify Directory and Package JSON
          command: |
            pwd
            ls -la
            cat package.json  # This will help verify the package.json is where you expect
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build  # If you have a build script

  test-node:
    executor: build-node  # Use the same executor
    steps:
      - checkout
      - run:
          name: Verify Directory and Package JSON
          command: |
            pwd
            ls -la
            cat package.json
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test