version: 2.1
executors:
  build-node:
    docker:
      - image: cimg/node:16.20.2
    working_directory: ~/project/BackendAPI/functions  # Updated path
  test-node:
    docker:
      - image: cimg/node:16.20.2
    working_directory: ~/project/BackendAPI/functions  # Updated path

jobs:
  build-node:
    executor: build-node
    steps:
      - checkout
      - run:
          name: Navigate to correct directory
          command: cd BackendAPI/functions
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build  # Add a build script if you have one

  test-node:
    executor: test-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "BackendAPI/functions/package-lock.json" }}
      - run:
          name: Navigate to correct directory
          command: cd BackendAPI/functions
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "BackendAPI/functions/package-lock.json" }}
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-node
      - test-node:
          requires:
            - build-node