version: 2.1

executors:
  build-node:
    docker:
      - image: cimg/node:16.20.2  # Use a specific version
    working_directory: ~/project  # Update this if necessary to the correct directory

  test-node:
    docker:
      - image: cimg/node:16.20.2  # Use the same node version for consistency
    working_directory: ~/project  # Update this to the directory where package.json is located

jobs:
  build-node:
    executor: build-node
    steps:
      - checkout
      - run:
          name: Check directory structure
          command: ls -la /home/circleci/project/BackendAPI/functions  # Verify if package.json exists
      - run:
          name: Install Dependencies
          command: npm install
      # Uncomment and adjust this if you want to run ESLint during the build
      #- run:
      #    name: Run ESLint
      #    command: npx eslint .

  test-node:
    executor: test-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "BackendAPI/functions/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - BackendAPI/functions/node_modules
          key: v1-deps-{{ checksum "BackendAPI/functions/package-lock.json" }}
      - run:
          name: Run Tests
          command: npm test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploy your app here"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-node
      - test-node:
          requires:
            - build-node