version: 2.1
executors:
  build-node:
    docker:
      - image: cimg/node:16.20.2  # Use a specific version
    working_directory: ~/project
  test-node:
    docker:
      - image: cimg/node:16.20.2  # Use a specific version
    working_directory: ~/project

jobs:
  build-node:
    executor: build-node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd BackendAPI/functions
            npm install
     # - run:
     #     name: Run ESLint
     #     command: |
     #       cd BackendAPI/functions
     #       npx eslint .

  test-node:
    executor: test-node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd BackendAPI/functions
            npm install
      - run:
          name: Install Jest
          command: |
            cd BackendAPI/functions
            npm install --save-dev jest
      - run:
          name: Debug Project Setup
          command: |
            cd BackendAPI/functions
            ls -la
            cat package.json

      - run:
          name: Run Tests
          command: |
            cd BackendAPI/functions
            npm test


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-node
      - test-node:
          requires:
            - build-node
          steps:
            - checkout
            - run:
                name: Clear NPM Cache
                command: |
                  cd BackendAPI/functions
                  npm cache clean --force