version: 2.1

executors:
  build-node:
    docker:
      - image: cimg/node:16.20.2  # Node.js version for backend
    working_directory: ~/project

  android-executor:
    docker:
      - image: cimg/android:33.0.2  # Android image with SDK
    working_directory: ~/project

jobs:
  build-node:
    executor: build-node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd BackendAPI/functions
            npm install

  build-android:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Set Up Gradle
          command: |
            mkdir -p ~/.gradle
            echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties
            echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Build Android App
          command: ./gradlew assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

  test-android:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - run:
          name: Run Instrumentation Tests
          command: ./gradlew connectedDebugAndroidTest

  deploy:
    executor: build-node
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploy your app here"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-node
      - build-android
      - test-android:
          requires:
            - build-android
      - deploy:
          requires:
            - build-node
            - test-android
