version: 2.1

executors:
  build-node:
    docker:
      - image: cimg/node:16.20.2  # Use Node.js version compatible with your project
    working_directory: ~/project

jobs:
  build-node:
    executor: build-node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd BackendAPI/functions
            npm install

  test-node:
    executor: build-node  # Fix reference to the existing executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "BackendAPI/functions/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            cd BackendAPI/functions
            npm install
      - save_cache:
          paths:
            - BackendAPI/functions/node_modules
          key: v1-deps-{{ checksum "BackendAPI/functions/package-lock.json" }}
      - run:
          name: Run Tests
          command: |
            cd BackendAPI/functions
            npm test

  deploy:
    executor: build-node  # Ensure deploy job uses an executor
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploy your app here"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-node
      - test-node:
          requires:
            - build-node
